### Crear un array a partir de una lista

# CLASE 07 Creación de Arrays
## Prof. Andrés Mena Abarca
### Estudiantes: José Francisco Morales Milanes

In [1]:
import numpy as np


### Crear un array de ceros de tamaño 5x5

In [2]:
#Código crear un array de ceros de tamaño 5x5
array_ceros = 0
#Código crear un array de ceros de tamaño 5x5
array_ceros = np.zeros((5,5))
print(array_ceros)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Crear un array de unos de tamaño 3x3

In [3]:
#Código crear un array de unos de tamaño 3x3

#Código crear un array de unos de tamaño 3x3
array_unos = np.ones((5,3))
print(array_unos)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Crear un array con valores espaciados uniformemente de 0 a 9

In [ ]:
#Código rear un array con valores espaciados uniformemente de 0 a 9


### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [ ]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1


# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [ ]:
array_1 = np.array([5,4,2])
array_2 = np.array([6,4,9])

#Código realizar una suma, resta, multiplicación y división entre dos arrays
array_numeros = np.array([5,2,4,1,3])
media = np.mean(array_numeros)
print(f'la media aritmetica es {media}')

promedio = np.average(array_numeros)
print(f'el promedio es {promedio}')
# Salida
suma = np.sum(array_numeros)
print(f'la suma de la coleccion es {suma}')

min = np.min(array_numeros)
print(f'el valor minimo es {min}')

maximo = np.max(array_numeros)
print(f'el valor maximo es {maximo}')
#print("La suma es: ",suma)
#print("La resta es: ",resta)
#print("La multiplicacion es: ",multiplicacion)
#print("La division es: ",division)



la media aritmetica es 3.0
el promedio es 3.0
la suma de la coleccion es15
el valor minimo es 1
el valor maximo es 5


# calcular la similitud de cada pelicula con los gustos de mariana
# preferencias peliculas mariana accion comedia drama

In [ ]:
mariana =  np.array([7,9,2])

avatar = np.array([10,1,5]) #mas accion y menos comedia
brave_heart = np.array([8,1,7])

similitud_p1 = np.dot(mariana,avatar)
similitud_p2 = np.dot(mariana,brave_heart)

print(f'similitud de preferencias avatar : {similitud_p1}')
print(f'similitud de preferencias brave_heart : {similitud_p2}')

if similitud_p1 > similitud_p2:
        print("Recomendamos  avatar")
else:
        print("Recomendamos brave_heart ")



similitud de preferencias avatar : 89
similitud de preferencias avatar : 79
Recomendamos  avatar


# calcular coeficiente de correlación 
## Tipo de cambio de dolar y indice precios al consumidor

In [14]:
tipo_cambio = np.array([506.96,505.00,504.27,505.52,506.23,506.23,506.23,506.58,506.87,507.25])
ipc = np.array([109.46,109.55,109.71,109.57,109.33,108.85,109.36,110.39,110.79,110.79])

#calcular coeficiente de correlación tienen que tener la misma cantidad de elementos
correlacion = np.corrcoef(tipo_cambio,ipc)[0,1] # 0 es q no hay 1 influye un poco 
print(f'Coeficiente de correlacion {correlacion:.2f}') # es de 0.3.2f para poner 2 decimales

Coeficiente de correlacion 0.40


# estudio de horas vrs notas
#datos quiero estudiar 2 situaciones las horas de estudio que aplique y las notas que tengo por materia

In [15]:
horas_estudio = np.array([1,2,3,4,5,6,7,8,9,10])
notas = np.array([50,55,60,63,67,72,75,78,81,85])

#calculo del crecimiento del promedio por horas de estudio.
#diferencia entre los puntajes nos va a dar una variacion incremento o decremento

diferencias_Notas = np.diff(notas) # entre la nota mas bajas consecutivas
incremento_notas = np.average(diferencias_Notas) # media ponderada
print(diferencias_Notas)

proyeccion_estudio = 12 

nota_estimada = (proyeccion_estudio -  max(horas_estudio)) * incremento_notas + max(notas) # este es el incremento que voy a tener en la nota 12 - 10 nota maxima
nota_estimada_Minimo = (horas_estudio[0] - proyeccion_estudio) * incremento_notas + notas[0] # este es el incremento que voy a tener en la nota 12 - 10 nota maxima
print(f'el incremento del promedio por cada hora de estudio es {incremento_notas:.2f}')
print(f'la nota esperada {nota_estimada:.2f}')
print(f'la nota esperada minima es {nota_estimada_Minimo:.2f}')

[5 5 3 4 5 3 3 3 4]
el incremento del promedio por cada hora de estudio es 3.89
la nota esperada 92.78
la nota esperada minima es 7.22


In [ ]:
#Calcular el producto punto de dos arrays


In [ ]:
#Transponer un array


# Operaciones Estadísticas

In [5]:
#Calcular la media, suma, valor mínimo y valor máximo de un array


# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])

# Calcular la media

media = np.mean(array_numeros)
print(f'la media aritmetica es {media}')

# Calcular la suma
suma = np.sum(array_numeros)
print(f'la suma de la coleccion es{suma}')

# Calcular el valor mínimo
min = np.min(array_numeros)
print(f'el valor minimo es {min}')

# Calcular el valor máximo
maximo = np.max(array_numeros)
print(f'el valor maximo es {maximo}')



la media aritmetica es 3.0
la suma de la coleccion es15
el valor minimo es 1
el valor maximo es 5


In [12]:
#Cambiar la forma de un array "reshape"

# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Nueva forma deseada (2 filas y 3 columnas)
#Cambiar la forma de un array "reshape"

array_reshapeado = array_original.reshape(3,2)

#Imprimir el array original y el reshapeado
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)


Array original: [1 2 3 4 5 6]
Array reshapeado: [[1 2]
 [3 4]
 [5 6]]


# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [ ]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2

#print(determinante)

### Calcular la matriz inversa de una matriz 3x3

In [ ]:
# Definir la matriz 3x3


# Calcular la matriz inversa


# Imprimir la matriz inversa



### Calcular los valores propios y vectores propios de una matriz 4x4

In [ ]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

# Funciones Universales

In [ ]:
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular el seno de los ángulos


# Calcular el coseno de los ángulos


# Calcular la exponencial de los ángulos


# Calcular el logaritmo natural de los ángulos




In [ ]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Obtener la primera fila del array


# Obtener la última columna del array
  # [3, 6, 9]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]

# Imprimir los subconjuntos de datos extraídos


# Generación de Números Aleatorios

In [ ]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100


In [ ]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1


In [ ]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)

